name: CI

on:
  push:
    paths-ignore: ['**/*.md']
  pull_request:
    paths-ignore: ['**/*.md']
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    container: swift:5.10
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: swift build
