name: CI

on:
  push:
    paths-ignore: ['**/*.md']
  pull_request:
    paths-ignore: ['**/*.md']
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    container: swift:5.9
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: swift build

  macos:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        if: runner.os == 'macOS'
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        # Current encounters errors in civetweb.
        continue-on-error: true
        run: |
          swift build && exit 0 || echo "::error:: Build step failed"

  windows:
    runs-on: windows-latest
    steps:
      - uses: compnerd/gha-setup-swift@main
        if: runner.os == 'Windows'
        with:
          branch: swift-5.9-release
          tag: 5.9-RELEASE
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: swift build
